### PR TITLE
Add the various parameter `in` operators for query, path, header, bod…

### PR DESCRIPTION
**Pull request by allen-munsch**
…y, form

For example, something like:

```
  parameters:
    x_org:
      name: x-org
      in: header
      description: list of organization ids
      required: false
      schema:
        type: array
        items:
          type: integer
          format: int32
    x_org_query:
      name: x-org-query
      in: query
      description: list of organization ids in the query
      required: false
      schema:
        type: array
        items:
          type: integer
          format: int32
    x_org_body:
      name: x-org-body
      in: body
      description: list of organization ids in the body
      required: false
      schema:
        type: array
        items:
          type: integer
          format: int32
```

### CODE REVIEW

**Comment by koxudaxi** [comment]
@allen-munsch 
Thank you for creating this PR.
Would you please fix the unittest?
Or, If I can get the time for this weekend then I will do it.

**Comment by allen-munsch** [comment]
@koxudaxi i'll try taking a look today

**Comment by allen-munsch** [comment]
@koxudaxi i don't know how to read this : https://github.com/koxudaxi/fastapi-code-generator/pull/162/checks?check_run_id=2696380246

so I'm not sure how to fix it.

**Comment by koxudaxi** [comment]
@allen-munsch 
The error comes from coverage is decrease.
Currently, this project doesn't reach coverage 100%.
I ignored the error.

I have released a new version `0.2.6`

Thank you very much :smile:

**Pull request merged**
