### PR TITLE
Add additional responses

### PR DESCRIPTION
**Pull request by rominf**
See https://fastapi.tiangolo.com/advanced/additional-responses/

Existing tests were updated to match OpenAPI schema more.

### CODE REVIEW

**Comment by LongBeachHXC** [comment]
@koxudaxi I also need this feature...what is the status on this PR?

**Comment by koxudaxi** [comment]
I'm sorry. I'm very busy🙇
I will release it as soon as possible by this weekend.

**Comment by LongBeachHXC** [comment]
@rominf @koxudaxi 

I've been testing this PR out and there are two things I've noticed so far.

1. When an operation has `additional_responses` and you are building the function there isn't a return type annotation. Does it make sense to use the Union type in these instances?
```
def {{operation.function_name}}({{operation.snake_case_arguments}}){% if operation.additional_responses %} -> Union[{{operation.response}},{{operation.additional_responses.values()|map(attribute='model')|unique|join(', ')}}] {% else %} -> {{operation.response}}{% endif %}:
```
2. I'm seeing some funny behavior with the root (`/`) endpoint. The operation.snake_case_path gets rewritten as a long auto generated string instead of just `/`
```
'/#-datamodel-code-generator-#-root-#-special-#'
```

**Comment by rominf** [comment]
@LongBeachHXC I've fixed (1) and also made my code cleaner. As for (2), I believe it's unrelated to this PR.

**Comment by LongBeachHXC** [comment]
@rominf I'm noticing the following in my use case. I have an endpoint with many responses but the same response object.

```
responses={
        '403': {'model': ErrorContainer},
        '422': {'model': ErrorContainer},
        '500': {'model': ErrorContainer},
    }

) -> Union[User, ErrorContainer, ErrorContainer, ErrorContainer]:
```

**Comment by rominf** [comment]
@LongBeachHXC Fixed.

**Comment by rominf** [comment]
Applied reformat.

**Comment by rominf** [comment]
I don't know what is this, and how to fix it :-(
image

**Comment by koxudaxi** [comment]
@rominf 
Thank you for fixing the problem.
We just met the error.

I guess the error is the same. 
https://stackoverflow.com/a/69913764

I will create a PR to fix the Black problem.

**Comment by koxudaxi** [comment]
@rominf 
I just released the new version 0.3.1
Thank you very much.
https://github.com/koxudaxi/fastapi-code-generator/releases/tag/0.3.1

**Pull request merged**
